version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: kp-container
    environment:
      POSTGRES_DB: postgre
      POSTGRES_USER: postgre
      POSTGRES_PASSWORD: postgre
    ports:
      - "5432:5432"
    volumes:
      - ./data:/docker-entrypoint-initdb.d
